name: Release 💨

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    uses: ./.github/workflows/make.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
#  release:
#    needs: build
#    name: Release to GitHub 🚀
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/release'
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Download Windows Artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: Build-StandaloneWindows64
#          path: build/StandaloneWindows64
#      - name: Download OSX Artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: Build-StandaloneOSX
#          path: build/StandaloneOSX
#      - uses: papeloto/action-zip@v1
#        with:
#          files: build/StandaloneWindows64/
#          dest: TowerDefenseWindows.zip
#      - uses: papeloto/action-zip@v1
#        with:
#          files: build/StandaloneOSX/
#          dest: TowerDefenseOSX.zip
#      - name: Release 🚀
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "*.zip"
#          token: ${{ secrets.GITHUB_TOKEN }}
#          name: Release ${{needs.build.outputs.buildVersion}}
#          tag: ${{needs.build.outputs.buildVersion}}
